baseurl = "https://godotmisogi.github.io/bloggy/"
relativeURLs = false
languageCode = "en-uk"
title = "Arjit Seth"
paginate = 5
disqusShortname = "godotmisogi"

[taxonomies]
	tag = "tags"
	tutorial = "projects"

[params]
	showglobe = true

	# Google Analytics
    analytics = "UA-89998292-1"

    favicon = "favicon.ico"
    
	github = "https://github.com/GodotMisogi"
	twitter = "https://twitter.com/ArjitSeth"
	linkedin = "https://www.linkedin.com/in/arjit-seth"
	email = "arjitseth@gmail.com"
	
	header = "Thinking Out Loud"
	profilepic = "img/Logo.png"
	
	title = "GOOD VIBRATIONS"
	subtitle = "ARJIT SETH"
	author = "Arjit Seth"
	
	[[params.navlinks]]
	name = "About"
	url = "about"
	
	[[params.navlinks]]
	name = "Blog"
	url = ""
	
	[[params.navlinks]]
	name = "Projects"
	url = "tutorial/"

[blackfriday]
	extensions = ["hardLineBreak"]